### ISSUE TITLE
Add `docker prune` guidance to the troubleshooting guide

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/2u-tutor-adoption#126]
## Context

After using Tutor for a while (especially, after using different versions of it and/or using it alongside Devstack), it is common for one's Docker build cache (on Linux, `/var/lib/docker`) to become very large. Like, tens of gigabytes. After a while, this can fill up the developer's disk, causing a variety of strange system-wide problems.

There is a very simple solution to this problem: [pruning](https://docs.docker.com/engine/reference/commandline/system_prune/). In particular, it is good to run the following every month or so:
```
tutor ... start        # start Tutor so that the images you need are considered "in use"
docker system prune -a # deletes every container and image that isn't in use
```
This can free up dozens of gigabytes of disk space.

## Acceptance Criteria

Add this information to the troubleshooting guide in the official docs: https://docs.tutor.overhang.io/troubleshooting.html

**Comment by regisb** [comment]
I suggest to clear only the oldest images:

    docker image prune --all --force --filter until=72h

**Comment by ARMBouhali** [comment]
it appears docker uses image creation time for the `until` filter rather than kast use time;
I think we need  we need to employ an LRU cache eviction policy.

I found this tool which does the LRU part, so I am adding it to the discussion
https://github.com/stepchowfun/docuum

**Comment by regisb** [comment]
@ARMBouhali I followed your suggestion and started using docuum on my CI server a couple weeks ago. So far it's working great! Here's my docker-compose.yml:

```
services:
  docuum:
    image: docker.io/stephanmisc/docuum:latest
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/docuum:/root/.local/share/docuum
    command: "--threshold=100GB"
    restart: unless-stopped
```
